server:
  port: 8888
spring:
  cloud:
    config:
      server:
        git:
          uri: file://G:/workspace/idea-workspace/learning-config-server/src/main/resources
logging:
  level:
    ROOT: debug